apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

data:
  PGUSER: {{ .Values.overTheTopDatabase.auth.username | b64enc | quote }}
  PGPASSWORD: {{ .Values.overTheTopDatabase.auth.password | b64enc | quote }}
