apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: 'letsencrypt'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        {{- toYaml .Values.domains.hostNames | nindent 8 }}
      secretName: over-the-top-with-k8s-com
  rules:
    {{- range $host := .Values.domains.hostNames }}
    - host: {{ $host }}
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
    {{- end }}
