apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: over-the-top-with-k8s-com-tls
spec:
  secretName: over-the-top-with-k8s-com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: over-the-top-with-k8s.com
  dnsNames:
    - over-the-top-with-k8s.com
    - www.over-the-top-with-k8s.com
