apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: "tonivrd/over-the-top-with-k8s-client:{{ .Values.tag }}"
          ports:
            - containerPort: 3000
