name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  MYENV: ${{ (github.ref == 'refs/heads/master' && PROD) || (github.ref == 'refs/pull/2/merge' && QA) }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref == 'refs/heads/master' && PROD) || (github.ref == 'refs/pull/2/merge' && QA) }}
    steps:
      - name: print branch
        run: echo ${{ github.ref }}

      - name: test var
        run: echo ${{ env.MYENV }}

      - name: test env
        run: echo ${{ github.environment }}

      - name: test direct
        run: echo ${{ (github.ref == 'refs/heads/master' && PROD) || (github.ref == 'refs/pull/2/merge' && QA) }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build docker image for testing the client
        run: docker build -f ./client/Dockerfile.dev -t test/client ./client
        
      - name: Run tests
        run: docker run -e CI=true test/client npm run test

  build:
    name: Build docker images and push to docker repo
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      SHA: $(git rev-parse HEAD)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build all docker images for the project
        run: python -u ./scripts/build.py

      - name: Push all docker images to repo
        run: python -u ./scripts/push.py
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && github.event_name == 'push'
    environment:
      name: ${{ (github.ref == 'refs/heads/master' && 'PROD') || (github.ref == 'refs/heads/develop' && 'QA') }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # This step sets authentication creds for Google Cloud SDK (gcloud CLI) using a service account key
      - name: Set Service Key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      # This step authenticates with GCP using the creds from previous step and configures the gcloud CLI to use a specific GCP project
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}

      # This step is not needed since we use Docker Hub. If we use GCR or something similar we need to uncomment this step
      # This step configures Docker to authenticate with Google Container Registry (GCR) or Artifact Registry
      #- name: Set up Docker
      #  run: gcloud --quiet auth configure-docker

      # This step retrieves the GKE cluster credentials and sets up kubectl to work with retreived credentials
      # allowing it to interact with the specified cluster
      - name: Set up kubectl
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.CLUSTER_NAME }}
          location: ${{ vars.LOCATION }}

      - name: Install helm
        uses: azure/setup-helm@v4.2.0
        id: install

      - name: Set up infrastructure
        run: ./scripts/set_up_infra.sh

      - name: Deploy
        run: |
          helm upgrade --install over-the-top-with-k8s helm_charts/over-the-top-with-k8s/ --atomic \
            --set tag=$(git rev-parse HEAD) \
            --set overTheTopDatabase.auth.username=${{ secrets.PSQL_USER }} \
            --set overTheTopDatabase.auth.password=${{ secrets.PSQL_PASSWORD }} \
            --values helm_charts/over-the-top-with-k8s/values/${{ vars.VALUE_PATH }}
